### ISSUE TITLE
Is there a way to change the place of the legend? (below the graph)

### ISSUE THREAD

**Issue by estebancolla** [danbischof/stata-plottig#1]
Is there a way to change the place of the legend? (below the graph) I am combining several graphs, each with the plottig scheme. Useful space is lost if the legend is at the right (each graph is too narrow). I like the scheme but I would prefer to have the legend below the graph. Is there a simple way to change this?

**Comment by extremeentrance** [comment]
Yes, of course. Two options:
1) You use the code provided by Stata to change the location. I guess in your case you would want the legend on 6 o'clock using only a single row: `legend(rows(1) position(6))`
Put this code within the options of your figure `tw XYZ,` HERE
2) You open the plottig scheme file in a .txt editor and adapted the code itself. 

Notice, however, that using legends might not be the best way to communicate these infos to reades. Instead using text within the figure might often be a better option. Legends tend to distract readers y forcing them to look underneath/next to the actual content of the figure.

**Comment by estebancolla** [comment]
Provisionally I will consider option two. The reason is that the graphs are produced by another package (`synth_runner` +`single_treatment_graphs`) and I do not have direct control on their design.
But you are right: I have to figure out the best way to communicate the info. Thanks for your answer!
